version: '3.4'

services:
  mycar.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DbConnection=Server=msSqlDb;Database=MyCar;User Id=sa;Password=Mycar123@"
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
    expose:
    - 8000 
    restart: on-failure
    networks:
      - backend
    links: 
      - msSqlDb
     
  msSqlDb:
    container_name: msSqlDb
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1435:1433"
    restart: unless-stopped
    environment:
      SA_PASSWORD: "Mycar123@"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlserver-data1:/var/lib/sqlserver/data
    networks:
      - backend
    expose:
    - 1435

networks:
  backend:
    driver: "bridge"
