version: '3.4'

services:
  mycar.api:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "ConnectionStrings:DatabaseConnection=Server=db;Database=master;User Id=sa;Password=Mycar123@"
     - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
    depends_on:
       - db
    restart: on-failure
    networks:
      - backend
     
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Mycar123@"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlserver-data1:/var/lib/sqlserver/data
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
